development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: ENV['DATABASE_URL']
  #adapter: redis
  #url: redis://localhost:6379/1
  channel_prefix: moebi_production
